[package]
name = "leetcode1"
version = "0.1.0"
edition = "2021"

[dependencies]
llama-cpp = "0.1"                                  # Hypothetical #
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
